const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const window = {};
vm.runInNewContext(fs.readFileSync('crm-insights.js', 'utf8'), { window, Intl, Date, Map });
const report = { period: { from: '2026-01-01', to: '2026-12-31', timezone: 'Asia/Kolkata' }, metrics: { leadsAdded: 3, wonContracts: 2, confirmedClients: 1, wonMonthlyValue: 1000, pipelineMonthlyValue: 2000, missingAmounts: 1 }, unknownDates: { records: 1, wins: 0, outreach: 1 }, intake: [{ date: '2026-01-02', count: 3 }], wins: [{ date: '2026-01-02', count: 2, monthlyValue: 1000, missingAmounts: 1 }], stages: [{ stage: 'new', count: 3 }], outreach: [{ channel: '<script>', outcome: '=unsafe', count: 2, confirmed: 1 }] };
const html = window.CRMInsights.reports(report);
assert.ok(html.includes('Current snapshot'));
assert.ok(html.includes('rather than received revenue'));
assert.ok(html.includes('&lt;script&gt;'));
assert.ok(!html.includes('<script>'));
assert.equal((html.match(/data-report-table-body/g) || []).length, 3);
assert.ok((html.match(/data-crm-action="report-drill"/g) || []).length < 180);
const table = window.CRMInsights.table(report, 'intake');
assert.equal((table.match(/data-crm-action="report-drill"/g) || []).length, 60);
assert.ok(table.includes('2026-01-02</td><td>3'));
assert.ok(window.CRMInsights.table(report, 'intake', 'count', 360).includes('361–365'));
assert.ok(window.CRMInsights.csv(report).includes('"\'=unsafe"'));
const clients = window.CRMInsights.clients({ summary: { clients: 1, monthlyValue: 1000, count: 1, missingAmounts: 0, due: 0, missing: 1, expired: 0 }, records: [{ id: 'r', profile: { company: '<img onerror=unsafe>', email: 'demo@example.test' }, contracts: [{ id: 'd', name: 'Guarding', monthlyAmount: null, renewalState: 'missing' }] }], asOf: '2026-10-06' });
assert.ok(clients.includes('&lt;img onerror=unsafe&gt;'));
assert.ok(clients.includes('Not entered'));
assert.ok(clients.includes('Create renewal follow-up'));
console.log('CRM reports: truthful snapshots, escaping, bounded charts, lazy paginated tables, CSV and renewal states passed.');
