'use strict';
const assert = require('node:assert/strict'), fs = require('node:fs'), vm = require('node:vm');
const handler = require('../api/grok-voice');
process.env.OMNIDIM_SESSION_KEY = 'test-only-session-secret-with-32-characters';
const originalFetch = global.fetch;
let calls = [], who = 'account-a', rejected = false;
global.fetch = async (url, options) => {
  calls.push({ url, options });
  if (url.endsWith('/auth/v1/user')) return { ok: !rejected, json: async () => ({ id: who }) };
  return { ok: true, status: 200, json: async () => url.includes('client_secrets') ? { value: 'ephemeral-short-token', expires_at: 123 } : url.includes('phone-numbers') ? { phone_numbers: [{ phone_number_id: 'phone_1', phone_number: '+18005550199', sip_auth: { password: 'never-return-this' } }] } : { voices: [{ voice_id: 'eve', name: 'Eve', api_key: 'never-return-this' }] } };
};
async function invoke(body, { cookie = '', method = 'POST', origin = 'https://app.example', auth = 'Bearer test-jwt' } = {}) {
  calls = [];
  const res = { headers: {}, setHeader(k,v) { this.headers[k] = v; }, status(n) { this.code = n; return this; }, json(data) { this.data = data; return this; } };
  await handler({ method, body, headers: { host: 'app.example', origin, authorization: auth, cookie, 'content-type': 'application/json' } }, res);
  return res;
}
(async () => {
  const connected = await invoke({ action: 'connect', secret: 'private-xai-key' });
  assert.equal(connected.code, 200);
  assert.match(connected.headers['Set-Cookie'], /Secure; HttpOnly; SameSite=Strict/);
  assert(!JSON.stringify(connected.data).includes('private-xai-key'));
  assert(!JSON.stringify(connected.data).includes('never-return-this'));
  const cookie = connected.headers['Set-Cookie'].split(';')[0];
  assert.equal((await invoke({ action: 'token' }, { cookie })).code, 409);
  assert.equal(calls.length, 1, 'Charge confirmation must prevent token issuance');
  assert.equal((await invoke({ action: 'token', confirmed: true }, { cookie })).data.value, 'ephemeral-short-token');
  assert.equal(calls[1].url, 'https://api.x.ai/v1/realtime/client_secrets');
  assert.deepEqual(JSON.parse(calls[1].options.body), { expires_after: { seconds: 300 } });
  who = 'account-b'; assert.equal((await invoke({ action: 'token', confirmed: true }, { cookie })).code, 409); assert.equal(calls.length, 1);
  who = 'account-a';
  assert.equal((await invoke({ action: 'token', confirmed: true }, { cookie, origin: 'https://attacker.example' })).code, 403); assert.equal(calls.length, 0);
  rejected = true; assert.equal((await invoke(null, { cookie, method: 'GET' })).code, 401); rejected = false;
  assert.equal((await invoke({ action: 'token', path: 'https://evil.example', confirmed: true }, { cookie })).code, 422);
  assert.equal((await invoke({ action: 'numbers' }, { cookie })).data.numbers[0].id, 'phone_1');
  assert(!JSON.stringify((await invoke({ action: 'numbers' }, { cookie })).data).includes('never-return-this'));
  const context = { window: { addEventListener() {} }, document: { addEventListener() {}, getElementById() { return null; } } };
  vm.runInNewContext(fs.readFileSync('grok-voice-studio.js', 'utf8'), context);
  const p = { keyterms: 'Rudra24', pronunciation: 'Rudra24 = रुद्र', speed: 1.1, silence: 5, reminders: 2, duration: 180, voice: 'eve', language: 'hi', reasoning: 'none', follow: true, instructions: 'Only approved business facts', style: 'Natural Hindi', greeting: 'Namaste', collection: 'collection-1', search: false };
  const payload = context.window.GrokStudio.settings(p).session;
  assert.equal(payload.audio.input.format.rate, 16000); assert.equal(payload.audio.output.speed, 1.1);
  assert.equal(payload.replace.Rudra24, 'रुद्र'); assert.equal(payload.audio.input.transcription.language_hint, 'hi');
  assert.equal(payload.turn_detection.idle_timeout_ms, 5000); assert.equal(payload.tools[0].type, 'file_search');
  assert.throws(() => context.window.GrokStudio.settings({ ...p, speed: 10 }));
  assert.throws(() => context.window.GrokStudio.settings({ ...p, pronunciation: 'not a mapping' }));
  assert.throws(() => context.window.GrokStudio.settings({ ...p, keyterms: 'x'.repeat(51) }));
  const elements = Object.fromEntries(['vp-provider','vp-sarvam','vp-omnidimension','vp-grok'].map(id => [id, {}]));
  const tt = {}, status = {}, label = {}, controls = [{}]; let stopped = 0, refreshed = 0;
  const providerContext = { window: { GrokStudio: { stop() { stopped++; }, refresh() { refreshed++; } }, OmniStudio: { stop() {}, refresh() {} } }, localStorage: { setItem() {}, getItem() { return null; } }, document: { readyState: 'loading', addEventListener() {}, getElementById(id) { return elements[id]; }, querySelector(s) { return s.endsWith('.tt-grid') ? tt : s.endsWith('#tt-status') ? status : label; }, querySelectorAll() { return controls; } } };
  const providerSource = fs.readFileSync('sarvam-calling-ui.js', 'utf8');
  vm.runInNewContext(providerSource.slice(providerSource.indexOf('window.VoiceProvider =')), providerContext);
  providerContext.window.VoiceProvider.select('grok');
  assert.equal(elements['vp-grok'].hidden, false); assert.equal(elements['vp-omnidimension'].hidden, true);
  assert.equal(tt.hidden, true); assert.equal(controls[0].hidden, true); assert.equal(refreshed, 1);
  providerContext.window.VoiceProvider.select('omnidimension'); assert.equal(stopped, 1); assert.equal(elements['vp-grok'].hidden, true);
  let Processor;
  vm.runInNewContext(fs.readFileSync('clavis-pcm-player-worklet.js', 'utf8'), { AudioWorkletProcessor: class { constructor() { this.port = { postMessage(msg) { this.last = msg; } }; } }, registerProcessor(_name, type) { Processor = type; }, Int16Array });
  const player = new Processor();
  player.port.onmessage({ data: { type: 'chunk', audio: new Int16Array([1000,2000]).buffer } });
  player.process([], [[new Float32Array(128)]]);
  player.port.onmessage({ data: { type: 'position', item_id: 'assistant-1' } });
  assert.equal(player.port.last.played, 2, 'Interruption must count audio actually played, excluding silence');
  console.log('Grok checks passed: authenticated encrypted connection, tenant/CSRF boundary, charge confirmation, public API payload and actual playback position.');
})().catch(e => { console.error(e); process.exitCode = 1; }).finally(() => { global.fetch = originalFetch; });
