'use strict';
const assert = require('node:assert/strict');
const fs = require('fs');
const vm = require('vm');
const doc = new EventTarget();
const w = { document: doc, addEventListener() {}, location: {hash:''} };
const ctx = vm.createContext({window:w,document:doc,console,setInterval:()=>0,setTimeout,clearTimeout,AbortController,CustomEvent:class extends Event {constructor(n,o){super(n);this.detail=o.detail;}}});
for(const file of ['clavis-task-model.js','clavis-task-controller.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx);
const task=w.ClavisTask;
const id=task.begin('Find 20 leads in Delhi');
let runs=0, industries;
task.requestLeadScope(id,{industries:['ALL'],cities:['Delhi'],count:20},'Find 20 leads in Delhi',(_,action)=>{runs++;industries=action.industries;});
assert.equal(runs,0,'scope picker does not start a run');
assert.equal(task.Store.get(id).approval.multiSelect,true,'industries must support multi-selection');
task.toggleApprovalOption(id,'hotels');
task.toggleApprovalOption(id,'healthcare');
assert.equal(runs,0,'choosing multiple industries does not dispatch a search');
task.resolveApproval(id,task.approvalValues(id));
assert.equal(runs,1);
assert.deepEqual(Array.from(industries),['Hotels & Hospitality','Hospitals & Healthcare'],'selected industries reach the actual runner');
task.requestLeadScope(id,{industries:['ALL']},'',(_,action)=>{industries=action.industries;});
task.toggleApprovalOption(id,'hotels'); task.toggleApprovalOption(id,'all-buyers');
assert.deepEqual(Array.from(task.approvalValues(id)),['ALL'],'All replaces narrower industries');
task.toggleApprovalOption(id,'healthcare');
assert.deepEqual(Array.from(task.approvalValues(id)),['Hospitals & Healthcare'],'a specific industry replaces All');
console.log('Lead scope selection and explicit Start: passed');
