'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
let saved={locations:[],industries:[]}, launched;
const doc=new EventTarget();
const w={document:doc,location:{hash:''},addEventListener(){},UserStorage:{getJSON:()=>saved},SKYLARK_CONFIG:{DEFAULT_CITY:'Gurugram'}};
const ctx=vm.createContext({window:w,document:doc,console,setInterval:()=>0,setTimeout,clearTimeout,AbortController,CustomEvent:class extends Event{constructor(n,o){super(n);this.detail=o.detail;}}});
for(const file of ['page-agent.js','lead-candidate-domain.js','clavis-task-model.js','clavis-task-controller.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx);
assert.deepEqual(Array.from(w.AgentCtrl.getDefaults().locations),['Gurugram'],'empty saved selections use configured city');
assert.deepEqual(Array.from(w.AgentCtrl.getDefaults().industries),['ALL']);
assert.deepEqual(Array.from(w.LeadCandidateDomain.parseRequest('leads nikalo').cities),['Gurugram']);
saved={locations:['East Delhi'],industries:['Hotels']};
assert.deepEqual(Array.from(w.LeadCandidateDomain.parseRequest('leads nikalo').cities),['East Delhi'],'saved narrow location stays narrow');
w.RealScraper={isRunning:()=>false,setCallbacks(){},run:async plan=>{launched=plan;}};
const id=w.ClavisTask.begin('leads nikalo');
w.ClavisTask.requestLeadScope(id,{industries:['ALL'],count:3},'leads nikalo');
assert.match(w.ClavisTask.Store.get(id).approval.detail,/East Delhi/,'floating picker explains its default location');
w.ClavisTask.toggleApprovalOption(id,'all-buyers');w.ClavisTask.resolveApproval(id,w.ClavisTask.approvalValues(id));
assert.deepEqual(Array.from(launched.locations),['East Delhi']);assert.deepEqual(Array.from(launched.industries),['ALL']);assert.equal(launched.targetCount,3);
w.AgentCtrl.renderIndustryGrid=()=>{};w.AgentCtrl.startPipeline=function(){assert.ok(this.selectedIndustries.size);};
w.AgentCtrl.runFromChat({industries:['ALL']});
console.log('Lead defaults: empty settings, configured/saved city, broad-industry picker and actual launch preserve scope/count.');
