'use strict';
const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
const source = fs.readFileSync('clavis-canvas.js', 'utf8');
const start = source.indexOf('  function onMapClick(e)');
const end = source.indexOf('  function drawRoute(geo)', start);
const V = {routePicking:false, pts:[], body:{querySelector:()=>null}, map:null, routeRequestId:0};
let routes = 0;
const scope = vm.createContext({V, addPoint:p=>{V.pts.push(p);return p;}, route:()=>routes++, setChip:()=>{}});
vm.runInContext(source.slice(start, end), scope);
const event = {lngLat:{lat:28.6,lng:77.2},originalEvent:{target:{closest:()=>null}}};
scope.onMapClick(event);
assert.equal(V.pts.length,0,'ordinary map taps never create route endpoints');
scope.setRoutePicking(true); scope.onMapClick(event);
assert.equal(V.pts.length,1); assert.equal(routes,0);
scope.onMapClick(event);
assert.equal(routes,1); assert.equal(V.routePicking,false,'A/B selection exits after two points');
scope.onMapClick(event); assert.equal(routes,1,'later normal taps do not restart the route');
scope.clearRoute(); assert.equal(V.pts.length,0);
assert.match(source,/if \(!_keep\) \{ clearRoute\(false\); addPoint\(a\); addPoint\(b\); \}/,'voice/named routing remains independent of picking');
console.log('Map normal clicks, explicit A/B selection, cancellation, voice path: passed');
